version: '3'

services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    # Enable hot reloading
    command: npm run dev -- --host 0.0.0.0